services:
    db:
        image: postgres
        ports:
            - 5432:5432
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: classnitte
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data:
